// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEk9nXaV7-SA3cGcjWh-FHrtOLOfGUg34',
    appId: '1:618061235772:web:0f2a0f805624605beb2539',
    messagingSenderId: '618061235772',
    projectId: 'alucollab',
    authDomain: 'alucollab.firebaseapp.com',
    storageBucket: 'alucollab.firebasestorage.app',
    measurementId: 'G-0RK1XLWZS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC88wgjpsdJKiTVl8E7nDuas0T__MnnqkE',
    appId: '1:618061235772:android:5f4526a902ea0076eb2539',
    messagingSenderId: '618061235772',
    projectId: 'alucollab',
    storageBucket: 'alucollab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIAOhSfoYWtlVEpWDHm-HOTpOyg9qPy38',
    appId: '1:618061235772:ios:91a967feb5aa7330eb2539',
    messagingSenderId: '618061235772',
    projectId: 'alucollab',
    storageBucket: 'alucollab.firebasestorage.app',
    iosBundleId: 'com.example.alucollab',
  );
}
